syntax = "proto3";

package healthmonitor;

service HealthMonitorService{
  //simple rpc
  rpc FetchVitals(VitalsRequest) returns (VitalsResponse);
  
  //client streaming rpc
  rpc StreamHeartRate(stream HeartRateData) returns (HeartRateSummary);
}

message VitalsRequest{
  string patient_id =1;
}

message VitalsResponse {
  int32 heart_rate =1;
  int32 oxygen_level =2;
  int32 temperature =3;
}

message HeartRateData {
  int32 bpm = 1;
}

message HeartRateSummary {
  int32 average_heartrate =1;
  string risk_level =2;
  string recommendation =3;
}