syntax = "proto3";

package healthmonitor;

service HealthMonitorService {
  //simple rpc
  rpc FetchVitals (VitalsRequest) returns (VitalsResponse);
  
  //client streaming rpc
  rpc StreamHeartRate (stream HeartRateData) returns (HeartRateSummary);
}

message VitalsRequest {
  string patientid =1;
}

message VitalsResponse {
  int32 heartrate =1;
  int32 oxygenlevel =2;
  int32 temperature =3;
}

message HeartRateData {
  int32 bpm = 1;
}

message HeartRateSummary {
  int32 averageheartrate =1;
  string risklevel =2;
  string recommendation =3;
}